export const dom = {
  apiKeyInput: document.getElementById("apiKeyInput"),
  apiBaseUrlInput: document.getElementById("apiBaseUrlInput"),
  modelSelect: document.getElementById("modelSelect"),
  docFileInput: document.getElementById("docFile"),
  fileNameSpan: document.getElementById("fileName"),
  languageSelect: document.getElementById("language"),
  customPromptToggle: document.getElementById("customPromptToggle"),
  customPrompt: document.getElementById("customPrompt"),
  customPromptContainer: document.getElementById("custom-prompt-container"),
  titleSuggestionToggle: document.getElementById("titleSuggestionToggle"),
  translateBtn: document.getElementById("translateBtn"),
  newTranslationBtn: document.getElementById("newTranslationBtn"),
  statusDiv: document.getElementById("status"),
  resultArea: document.getElementById("resultArea"),
  translatedOutput: document.getElementById("translatedOutput"),
  cleanedOutputArea: document.getElementById("cleanedOutputArea"),
  cleanedOutput: document.getElementById("cleanedOutput"),
  cleanedCopyBtn: document.getElementById("cleanedCopyBtn"),
  cleanTranslatedContentBtn: document.getElementById(
    "cleanTranslatedContentBtn",
  ),
  seoTagsBtn: document.getElementById("seoTagsBtn"),
  storyQuizBtn: document.getElementById("storyQuizBtn"),
  copyBtn: document.getElementById("copyBtn"),
  saveNodeChangesBtn: document.getElementById("saveNodeChangesBtn"),
  uploadIcon: document.getElementById("uploadIcon"),
  clearFileBtn: document.getElementById("clearFileBtn"),
  titleSuggestionBtn: document.getElementById("titleSuggestionBtn"),
  titleSuggestionArea: document.getElementById("titleSuggestionArea"),
  titleSuggestionOutput: document.getElementById("titleSuggestionOutput"),
  suggestAgainBtn: document.getElementById("suggestAgainBtn"),
  uploadTab: document.getElementById("uploadTab"),
  pasteTab: document.getElementById("pasteTab"),
  uploadPanel: document.getElementById("uploadPanel"),
  pastePanel: document.getElementById("pastePanel"),
  pasteInput: document.getElementById("pasteInput"),
  manualChunkModeToggle: document.getElementById("manualChunkModeToggle"),
  manualChunkPanel: document.getElementById("manualChunkPanel"),
  manualChunkList: document.getElementById("manualChunkList"),
  addManualChunkBtn: document.getElementById("addManualChunkBtn"),
  addCommentBtn: document.getElementById("addCommentBtn"),
  commentModal: document.getElementById("commentModal"),
  commentHtmlInput: document.getElementById("commentHtmlInput"),
  processCommentBtn: document.getElementById("processCommentBtn"),
  commentCancelBtn: document.getElementById("commentCancelBtn"),
  commentSection: document.getElementById("commentSection"),
  formattedCommentsOutput: document.getElementById("formattedCommentsOutput"),
  commentActions: document.getElementById("commentActions"),
  translateAllCommentsGoogleBtn: document.getElementById(
    "translateAllCommentsGoogleBtn",
  ),
  translateAllCommentsAIBtn: document.getElementById(
    "translateAllCommentsAIBtn",
  ),
  toggleCommentsBtn: document.getElementById("toggleCommentsBtn"),
  evaluateBtn: document.getElementById("evaluateBtn"),
  evaluationResultArea: document.getElementById("evaluationResultArea"),
  evaluationOutput: document.getElementById("evaluationOutput"),
  toggleEvaluationBtn: document.getElementById("toggleEvaluationBtn"),
  detailedStatusContainer: document.getElementById("detailedStatusContainer"),
  characterCountContainer: document.getElementById("characterCountContainer"),
  totalCharCount: document.getElementById("totalCharCount"),
  timerDisplay: document.getElementById("timerDisplay"),
  qaSection: document.getElementById("qaSection"),
  qaQuestionInput: document.getElementById("qaQuestionInput"),
  qaAskBtn: document.getElementById("qaAskBtn"),
  qaAnswerOutput: document.getElementById("qaAnswerOutput"),
  storyDescriptionBtn: document.getElementById("storyDescriptionBtn"),
  storyDescriptionArea: document.getElementById("storyDescriptionArea"),
  storyDescriptionOutput: document.getElementById("storyDescriptionOutput"),
  storyDescriptionCopyBtn: document.getElementById("storyDescriptionCopyBtn"),
  storyDescriptionRegenerateBtn: document.getElementById(
    "storyDescriptionRegenerateBtn",
  ),
  seoTagsArea: document.getElementById("seoTagsArea"),
  seoTagsOutput: document.getElementById("seoTagsOutput"),
  seoTagsCopyBtn: document.getElementById("seoTagsCopyBtn"),
  storyQuizArea: document.getElementById("storyQuizArea"),
  storyQuizOutput: document.getElementById("storyQuizOutput"),
  storyMetadataArea: document.getElementById("storyMetadataArea"),
  storyTitleInput: document.getElementById("storyTitleInput"),
  storyGenreInput: document.getElementById("storyGenreInput"),
  generateStoryMetadataBtn: document.getElementById("generateStoryMetadataBtn"),
  storyMetadataOutput: document.getElementById("storyMetadataOutput"),
  storageIdInput: document.getElementById("storageIdInput"),
  storageIdMessage: document.getElementById("storageIdMessage"),
  refreshStorageBtn: document.getElementById("refreshStorageBtn"),
  storageRecordList: document.getElementById("storageRecordList"),
  historyImportFileInput: document.getElementById("historyImportFileInput"),
  importHistoryFileBtn: document.getElementById("importHistoryFileBtn"),
  selectHistoryDirectoryBtn: document.getElementById(
    "selectHistoryDirectoryBtn",
  ),
  historyFilePathLabel: document.getElementById("historyFilePathLabel"),
  historySearchNameInput: document.getElementById("historySearchNameInput"),
  historySearchUrlInput: document.getElementById("historySearchUrlInput"),
  historyGroupFilterSelect: document.getElementById("historyGroupFilterSelect"),
  historyResultCountLabel: document.getElementById("historyResultCountLabel"),
  toggleStorageCompactBtn: document.getElementById("toggleStorageCompactBtn"),
  toggleCompletedVisibilityBtn: document.getElementById(
    "toggleCompletedVisibilityBtn",
  ),
  historyStatsTotal: document.getElementById("historyStatsTotal"),
  historyStatsDone: document.getElementById("historyStatsDone"),
  historyStatsPending: document.getElementById("historyStatsPending"),
};
